### ISSUE TITLE
Batching/Sliding Window

### ISSUE THREAD

**Issue by logtd** [yrcong/flatten#2]
Hi all,

Thank you for publishing this code and researching this amazing tech.

Is there a recommended way to perform inference on batches of a video? e.g. process a video in chunks?

In the code there's references to `inter_frame` and `get_slide_window_indices`, but they're never used. 

Again, thank you for publishing this code. I've implemented it into ComfyUI a diffusion pipeline used by artists and creators. I'd like to share it with others, but without batching large GPUs can only handle ~40 frames.
https://github.com/logtd/ComfyUI-FLATTEN

Also, please let me know if I'm missing any citations, contributions, etc. Happy to add them as your research is what made that possible!

**Comment by yrcong** [comment]
Hello logtd, 

I am glad that you have interest in our model and welcome to integrate FLATTEN into ComfyUI!

For processing a video in chunks, TBH, we didn't test it. ```inter_frame``` and ```get_slide_window_indices``` are used for something else and left. 

I would like to suggest that you could do in this way:
Let's say there is a 100-frame video, you could chunk it into three clips: [1-40], [30-70], [60-100] and process them with FLATTEN in batch. Since there are overlaps between these chunks, the visual appearance should be somehow consistent. 

We will move on to optimize FLATTEN to make it more efficient:D

best regards,
Yuren

**Comment by logtd** [comment]
Thanks for your reply!

I've implemented a naive batching solution and it works somewhat. Will try to improve it over time.

One interesting thing I've found about Flatten is that while sampling you can use a sampling algorithm that adds additional noise as long as the noise is guided by optical flow/trajectories through frames. It allows the model to produce videos that can deviate from the source input but maintain consistency. Here's a simple (yet slow) implementation of it https://github.com/logtd/ComfyUI-FLATTEN/blob/main/utils/flow_noise.py

Again, thanks for open sourcing this code. Going to close the issue but feel free to reopen.

**Comment by yrcong** [comment]
Thanks for the information! Please let me know if you have other concerns. After ECCV I will have more time;D
